language: android

jdk:
  - oraclejdk8

android:
    components:
        - platform-tools
        - tools
        - build-tools-25.0.3
        - android-25
        - extra-android-m2repository
        - extra-android-support
        - extra-google-google_play_services
        - extra-google-m2repository

before_script:
   - echo "sdk.dir=$ANDROID_HOME" > local.properties
script:
   - ./gradlew check

before_cache:
  - rm -f $HOME/.gradle/caches/modules-2/modules-2.lock
cache:
  directories:
    - $HOME/.gradle/caches/
    - $HOME/.gradle/wrapper/
